#sudo is needed for some ansible plays in this role
#ip gives ip config to ansible, so that should be installed also
- name: install package
  package: name="sudo,iproute"
  register: probably_docker

- name: reread setup
  setup:
  when: probably_docker.changed

- name: install pure package
  package: name="{{PURE_URL}}"
  when: not NO_REPO
